name: flusion
channels:
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - lightgbm
  - matplotlib
  - nomkl
  - numpy
  - pandas
  - pytest
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - pymmwr
    - jax
    - jaxlib
    - numpyro
    - "--editable=git+https://github.com/elray1/sarix.git#egg=sarix"
    - "--editable=git+https://github.com/reichlab/timeseriesutils.git#egg=timeseriesutils"
    - "--editable=code/data-pipeline"
