name: flusion
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24
  - pandas
  - matplotlib
  - seaborn
  - pip
  - pip:
    - pymmwr
    - jax
    - jaxlib
    - numpyro
    - lightgbm
    - "--editable=git+https://github.com/elray1/sarix.git#egg=sarix"
    - "--editable=git+https://github.com/reichlab/timeseriesutils.git#egg=timeseriesutils"
